- hosts: localhost
  tasks:
    - name: Install elasticsearch
      kubernetes.core.helm:
        name: elasticsearch
        namespace: kube-system
        chart_ref: $HOME/workspace/helm-charts/elasticsearchyuuvis
        kubeconfig_path: "{{ kubeconfig }}"
        create_namespace: True
        wait: true
    - name: Install logstash
      kubernetes.core.helm:
        name: logstash
        namespace: kube-system
        chart_ref: $HOME/workspace/helm-charts/logstash
        kubeconfig_path: "{{ kubeconfig }}"
        create_namespace: True
        wait: true
        values_files: $HOME/workspace/helm-charts/logstash/examples/elasticsearch/values.yaml
    - name: Install kibana
      kubernetes.core.helm:
        name: kibana
        namespace: kube-system
        chart_ref: $HOME/workspace/helm-charts/kibana
        kubeconfig_path: "{{ kubeconfig }}"
        create_namespace: True
        wait: true
    - name: Install filebeat
      kubernetes.core.helm:
        name: filebeat
        namespace: kube-system
        chart_ref: $HOME/workspace/helm-charts/filebeat
        kubeconfig_path: "{{ kubeconfig }}"
        create_namespace: True
        wait: true
