- hosts: localhost
  tasks:
    - name: UnInstall filebeat
      kubernetes.core.helm:
        name: filebeat
        state: absent
        namespace: kube-system
        chart_ref: $HOME/workspace/elastichelmcharts/filebeat
        kubeconfig_path: "{{ kubeconfig }}"
        create_namespace: True
        wait: true
    - name: UnInstall logstash
      kubernetes.core.helm:
        name: logstash
        state: absent
        namespace: kube-system
        chart_ref: $HOME/workspace/elastichelmcharts/logstash
        kubeconfig_path: "{{ kubeconfig }}"
        create_namespace: True
        wait: true
        values_files: $HOME/workspace/elastichelmcharts/logstash/examples/elasticsearch/values.yaml
    - name: UnInstall kibana
      kubernetes.core.helm:
        name: kibana
        state: absent
        namespace: kube-system
        chart_ref: $HOME/workspace/elastichelmcharts/kibana
        kubeconfig_path: "{{ kubeconfig }}"
        wait: true
    - name: UnInstall elasticsearch
      kubernetes.core.helm:
        name: elasticsearch
        state: absent
        namespace: kube-system
        chart_ref: $HOME/workspace/elastichelmcharts/elasticsearch
        kubeconfig_path: "{{ kubeconfig }}"
        create_namespace: True
        wait: true
