- hosts: localhost
  tasks:
    - name: Install filebeat
      kubernetes.core.helm:
        name: filebeat
        namespace: kube-system
        chart_ref: $HOME/workspace/elastichelmcharts/filebeat
        kubeconfig_path: "{{ kubeconfig }}"
        create_namespace: True
        wait: true
#        values_files: $HOME/workspace/elastichelmcharts/logstash/examples/elasticsearch/values.yaml
