- hosts: localhost
  tasks:
    - name: Install logstash
      kubernetes.core.helm:
        name: logstash
        namespace: kube-system
        chart_ref: $HOME/workspace/helm-charts/logstash
        kubeconfig_path: "{{ kubeconfig }}"
        create_namespace: True
        wait: true
        values_files: $HOME/workspace/helm-charts/logstash/examples/elasticsearch/values.yaml
