- hosts: localhost
  tasks:
    - name: UnInstall logstash
      kubernetes.core.helm:
        name: logstash
        state: absent
        namespace: kube-system
        chart_ref: $HOME/workspace/elastichelmcharts/logstash
        kubeconfig_path: "{{ kubeconfig }}"
        create_namespace: True
        wait: true
        values_files: $HOME/workspace/elastichelmcharts/logstash/examples/elasticsearch/values.yaml
